version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - overuse-postgres:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - default
    ports:
      - 8080:8080
    

volumes:
  overuse-postgres:

networks:
  overuse-net:
    driver: bridge